name: Windows latest

on: workflow_dispatch

jobs:

  build-windows:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    
    steps:  
    - uses: msys2/setup-msys2@v2
    
    - uses: actions/checkout@v1

    #  with:
    #    update: true
    #- name: Create symbolic link for MSYS2
    #  shell: cmd
    #  run: mklink /D c:\msys64 d:\a\_temp\msys\msys64
    # - uses: actions/checkout@v1
    - name: Install dependencies
      # shell: msys2 {0}

      run: | 
        msys2 -c 'pacman -S --noconfirm make'
    - run: | 
        msys2 -c 'pacman -S --noconfirm mingw-w64-x86_64-gcc'
    - run: |
        msys2 -c 'pacman -S --noconfirm mingw-w64-x86_64-libusb-compat-git'
    - run: |
        msys2 -c 'pacman -S --noconfirm mingw-w64-x86_64-hidapi'
      
    #- name: configure
    #  run: ./configure
    - name: make
      run: |
        msys2 -c 'make TARGETOS=windows'
    #- name: make check
    #  run: make check
    #- name: make distcheck
    #  run: make distcheck
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: msigd executable
        path: msigd.exe
